name: Development Deploy

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  PROJECT_ID: maliev-website
  GAR_LOCATION: asia-southeast1
  REGISTRY_REPO: maliev-website-artifact-dev
  SERVICE: maliev-line-chatbot-service
  ENVIRONMENT: development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run linting
      run: |
        cd backend
        ruff check src/ tests/
        mypy src/

    - name: Run tests
      run: |
        cd backend
        pytest --cov=src --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
        flags: unittests
        name: codecov-development

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker to use gcloud as credential helper
      run: gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev

    - name: Create Dockerfile
      run: |
        cat > backend/Dockerfile << 'EOF'
        FROM python:3.11-slim

        # Set working directory
        WORKDIR /app

        # Install system dependencies
        RUN apt-get update && apt-get install -y \
            build-essential \
            curl \
            && rm -rf /var/lib/apt/lists/*

        # Copy requirements first for better caching
        COPY requirements.txt .
        COPY requirements-dev.txt .

        # Install Python dependencies
        RUN pip install --no-cache-dir -r requirements.txt

        # Copy application code
        COPY . .

        # Create non-root user
        RUN useradd --create-home --shell /bin/bash app \
            && chown -R app:app /app
        USER app

        # Health check
        HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
            CMD curl -f http://localhost:8000/health || exit 1

        # Expose port
        EXPOSE 8000

        # Run the application
        CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
        EOF

    - name: Build and push Docker image
      run: |
        cd backend
        IMAGE_TAG="dev-$(date +%Y%m%d)-${GITHUB_SHA:0:7}"
        IMAGE_URI=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REGISTRY_REPO/$SERVICE:$IMAGE_TAG
        
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI
        
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Update GitOps Repository
      uses: actions/checkout@v4
      with:
        repository: MALIEV-Co-Ltd/maliev-gitops
        token: ${{ secrets.GITOPS_TOKEN }}
        path: gitops

    - name: Update development deployment
      run: |
        cd gitops
        
        # Configure git
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@maliev.com"
        
        # Update image in kustomization.yaml
        KUSTOMIZATION_FILE="3-apps/line-chatbot-service/overlays/development/kustomization.yaml"
        
        if [ -f "$KUSTOMIZATION_FILE" ]; then
          # Update or add newTag
          if grep -q "newTag:" $KUSTOMIZATION_FILE; then
            sed -i "s|newTag:.*|newTag: $IMAGE_TAG|" $KUSTOMIZATION_FILE
          else
            sed -i "/newName:/a \  newTag: $IMAGE_TAG" $KUSTOMIZATION_FILE
          fi
          
          # Commit and push changes
          git add $KUSTOMIZATION_FILE
          git commit -m "🚀 Deploy to development: $SERVICE:$IMAGE_TAG

          - Environment: Development
          - Image: $IMAGE_URI
          - Commit: ${{ github.sha }}
          - Branch: develop
          
          🤖 Generated with [Claude Code](https://claude.ai/code)
          Co-Authored-By: Claude <noreply@anthropic.com>"
          git push
        else
          echo "❌ Kustomization file not found: $KUSTOMIZATION_FILE"
          exit 1
        fi

    - name: Development deployment summary
      run: |
        echo "✅ Development deployment completed successfully!"
        echo "🚀 Image: $IMAGE_URI"
        echo "🌐 URL: https://dev.line-chatbot.maliev.com"
        echo "📝 Commit: ${{ github.sha }}"